# -*- coding: utf-8 -*-
# Joke game
print('What do you get when you cross a snowman with a vampire?')
input()
print('Frosbite!')
print()
print("Whats do dentist call a astronaut's cavity")
input()
print("A black hole!")
print()
print("Knock knock.")
input()
print("Who's there?")
input()
print('Interrupting cow.')
input()
print('Interrupting cow wh', end='')
print('-MOO!')
